# Generated by Django 2.1.2 on 2018-11-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskPupkin', '0002_auto_20181105_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=models.ImageField(default='static/usr_img/default', upload_to='static/usr_img'),
        ),
    ]
