# Generated by Django 2.1.2 on 2018-11-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AskPupkin', '0003_auto_20181106_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='correct',
            new_name='is_correct',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='name',
        ),
    ]
