# Generated by Django 2.1.2 on 2018-11-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AskPupkin', '0004_auto_20181106_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='title',
        ),
    ]
